# Generated by Django 4.2.16 on 2024-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
