# Generated by Django 4.2.16 on 2024-11-04 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 20, 56, 16, 942461)),
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 20, 56, 16, 942461)),
        ),
    ]
